{"p": "The exhibition is co-organized by the Municipal People's Government of Zhangjiakou, the China National Tourist Office in Singapore, the China Cultural Centre in Singapore and China Express Travel (Singapore) Pte Ltd."}
{"p": "Through a series of photos of Winter Olympics venues in Zhangjiakou in North China's Hebei province and the city\u2019s places of interest, natural scenery, local customs, and intangible cultural heritage, the show aims to interpret the spirit of Beijing Winter Olympics for Singaporeans."}
{"p": "Xiao Jianghua, director of the China Cultural Centre and the China National Tourist Office in Singapore, Ellen Lee Geck Hoon, president of the Singapore Table Tennis Association and a former member of Parliament, the Singaporean table tennis player Clarence Chew Zhe Yu, and other guests attended the event."}
{"p": "Addressing the ceremony, Xiao said that Beijing has become the first city to host both the Summer and Winter Olympic Games. After six years of preparations, the Beijing 2022 Olympics will be an unforgettable event for global Winter Olympic athletes and ice and snow sports lovers. Although no Singaporean athletes have qualified for the Games, Singapore Changi Airport will become a hub in the region for the event. Singapore Airlines' charter service will not only facilitate the participants of the Winter Olympics from many countries in the region and the southern hemisphere, but also provide valuable support for the Beijing Winter Olympics."}
{"p": "Hoon said that as a representative of the sports community in Singapore, she paid close attention to and was very impressed with the 2008 Beijing Summer Olympics. She praised the Chinese government and its people for building high-level venues and stadiums and making full preparations for the Games, and expressed her full confidence in the success of the Beijing Winter Olympics."}
{"p": "Zhangjiakou, with rich cultural and natural resources, is only 180 kilometers away from Beijing. It boasts nine ski resorts and ski runs totaling more than 160 kilometers in length, forming the largest winter sports venue cluster in the country."}
{"p": "The exhibition will run through Jan 24."}
{"p": "11 am-5 pm, closed on Mondays. China Cultural Centre in Singapore.\u00a0"}
{"p": "During this year's two sessions, China's most important annual political event, foreign ambassadors to China put forward some of their concerns. The concerns, ranging from deepening economic and trade cooperation to expanding cultural exchanges, were answered by Chinese experts."}
{"p": "Tuvshin Badral, the ambassador of Mongolia to China, asked what China plans to do to enhance the coherence between policies of the Belt and Road Initiative and the national development policy of Mongolia."}
{"p": "Liu Baocheng, director of the Center for International Business Ethics at the University of International Business and Economics, responded to this question. Watch the video to hear what he said."}
{"p": "In July 2019, an outbreak of \"e-cigarette pneumonia\" was reported in the US. In November, a plane carrying frozen lobsters from the US, landed in China. One month later,data on the \"e-cigarette pneumonia\" stopped in the US and China had an outbreak of COVID-19. What is the connection between this shipment of imported lobsters and the COVID-19 outbreak?"}
{"p": "During this year's two sessions, China's most important annual political event, foreign ambassadors to China put forward some of their concerns. The concerns, ranging from deepening economic and trade cooperation to expanding cultural exchanges, were answered by Chinese experts."}
{"p": "Raja Nushirwan, ambassador of Malaysia to China, said he was interested in how will China support cultural and people-to-people exchanges with other countries especially with Malaysia. In December 2020, the two countries submitted a successful joint application to UNESCO for designation of the Wangchuan ceremony as an intangible cultural heritage for mankind."}
{"p": "Guo Yi, Secretary of the Party Committee of School of International Economics and Management, Beijing Technology and Business University, responded to this question. Watch the video to hear what he said."}
{"p": "For Kenyans like Mbithe Kyule struggling to make ends meet due to the country's high inflation, a conflict on another continent is about to make daily life a lot more difficult."}
{"p": "Kyule, who lives in the capital, Nairobi, usually gets by selling popsicles and living as frugally as she can. However, there has been a recent surge in the price of basic commodities such as sugar, cooking oil, rice and corn flour."}
{"p": "In a matter of months the price of a liter of cooking oil has risen sharply from $1.30 to $3.10, while the cost of a carton of milk has increased from 40 cents to 50 cents."}
{"p": "\"I usually earn $2 to $5 per day and only concentrate on putting food on the table now. I no longer save,\" Kyule said."}
{"p": "As in many other parts of the world, the inflation rate in Kenya is high, with people also suffering from the impact of the COVID-19 and millions of job losses as well as the lingering effects of a drought."}
{"p": "Food prices in Kenya and the whole of Africa are expected to continue rising over the next few months, due to disruptions to food supplies caused by the Russia-Ukraine conflict, international organizations and experts have warned. Many African countries rely heavily on imports of grains such as wheat and corn."}
{"p": "Kenya's consumer price index stood at 5.08 percent in February, mainly driven by increases in commodity prices, according to the Kenya National Bureau of Statistics."}
{"p": "The price of food and non-alcoholic beverages increased by 8.7 percent year-on-year, while furnishings, household equipment and routine household maintenance costs rose 5.41 percent, the bureau said."}
{"p": "Using the hashtag #lowerfoodprices, Kenyans have taken to social media to protest the high cost of living. \"I am concerned that 1,000 shillings ($8.75) can't buy basic things for my family to last two days,\" one user called Prudent Lilly wrote."}
{"p": "In neighboring Uganda, members of Parliament are urging the government to take action over high commodity prices."}
{"p": "At a March 2 parliamentary sitting, MPs highlighted how the high prices had impacted the citizens, saying the cost of fertilizer, for instance, had increased more than fivefold."}
{"p": "The United Nation's Food and Agriculture Organization's food price index, which tracks the international prices of items, said global food prices rose to a record high in February, led by vegetable oils and dairy products."}
{"p": "Upali Galketi Aratchilage, an economist at the FAO, said food price inflation is coming from outside food production, particularly in the energy, fertilizer and feed sectors. \"All these factors tend to squeeze profit margins of food producers, discouraging them from investing and expanding production,\" Aratchilage said in a statement on March 4."}
{"p": "The World Bank has warned that the Russia-Ukraine conflict is likely to increase the price of food in emerging markets and developing economies."}
{"p": "Global commodity markets are facing a reduction in grain supplies, higher energy prices, higher fertilizer prices, and trade disruption due to closures of major ports."}
{"p": "Gilbert F. Houngbo, president of the International Fund for Agricultural Development, said continuation of the conflict between Russia and Ukraine will be catastrophic for the world, particularly for people already struggling to feed their families in African countries."}
{"p": "\"Forty percent of wheat and corn exports from Ukraine go to the Middle East and Africa, which are already grappling with hunger issues, and where further food shortages or price increases could stoke social unrest,\" Houngbo said in a statement."}
{"p": "Paloma Fernandes, Kenya's Cereal Millers Association chief executive, warned the Russia-Ukraine conflict will affect the cost of production in East Africa and further increase the cost of living in the region."}
{"p": "\"Our region relies on both Ukraine and Russia as key exporters for grain, as they account for 33 percent of global wheat supplies,\" Fernandes said at a news conference."}
{"p": "United Nations Secretary-General Antonio Guterres called for immediate peace negotiations to end the conflict at a news conference in New York on March 14."}
{"p": "He said 45 African and less developed countries import at least one-third of their wheat from Ukraine and Russia, and the conflict is worsening food shortages in poorer countries."}
{"p": "\"Many African countries and poor countries are dependent on wheat production in Russia and Ukraine, but now they are at risk because of the war,\" Guterres said."}
{"p": "\u00a0"}
{"p": "In efforts to curb the spread of polio after an outbreak in Malawi, the United Nations Children's Fund, partners and respective governments have launched a vaccination campaign targeting the southeastern African country and its neighbors Mozambique, Tanzania and Zambia."}
{"p": "In the first round of the mass vaccination campaign which began on Sunday, more than 9 million children under the age of 5 will be vaccinated against the disabling and life-threatening disease in the four countries."}
{"p": "Three more rounds of vaccination targeting 20 million children, including Zimbabwe, will follow in April, June and July."}
{"p": "UNICEF said it has procured more than 36 million doses of polio vaccine for the first two rounds."}
{"p": "The vaccination campaign follows after Malawi reported a confirmed case of Type 1 wild poliovirus in a 3-year-old girl in the capital Lilongwe on Feb 17. The confirmation caused alarm because it was the first detection of a polio case in Africa since 2016 and also after the continent was declared free of indigenous wild polio in August 2020."}
{"p": "Additionally, detection of a case outside the world's two remaining endemic countries, Pakistan and Afghanistan, represented an emergency that requires effective response to prevent its spread, according to the World Health Organization."}
{"p": "Genetic sequencing of the Malawi case linked the virus to a strain circulating in Pakistan's Sindh province in 2019, indicating that it was an imported virus."}
{"p": "Polio is a viral disease with no cure. It invades the nervous system and can cause irreversible paralysis mainly in children and teenagers up to 15 years of age. It also has the potential to infect immunocompromised adults."}
{"p": "\"UNICEF is working closely with governments and partners to do everything possible to stop the virus in its tracks,\" said Mohamed Fall, the agency's regional director for eastern and southern Africa, in a statement on Sunday."}
{"p": "Polio can be contracted through drinking water that is contaminated with the feces of someone who carries the virus. Children under the age of 5 and those living in areas with poor sanitation are most at risk."}
{"p": "\"A regional response is vital as polio is extremely contagious and can spread easily as people move across borders,\" Fall said."}
{"p": "\"There is no cure for polio, but the vaccine protects children for life. We are working with the World Health Organization and other partners to make sure parents, as well as community and religious leaders, know how important it is that every child receives their vaccine.\""}
{"p": "Matshidiso Moeti, the WHO's regional director for Africa, said on Friday that more than 80 million doses of the bivalent oral polio vaccine will be administered in the four-round vaccination drive."}
{"p": "The WHO said the polio vaccination campaign is aimed at reaching children who are either not immunized or only partially protected, and to boost immunity in those who have been immunized."}
{"p": "Data published by the WHO and UNICEF in July indicated that around 7.7 million African children missed out on vital first doses of Diphtheria-Tetanus-Pertussis, measles and polio vaccines in 2020 due to disruptions to health services caused by the COVID-19 pandemic."}
{"p": "China is looking forward to working closely with Kenya to realize stability in the Horn of Africa region, a Chinese official said."}
{"p": "Xue Bing, the Chinese special\u00a0envoy for the Horn of Africa, commended Kenya for its continued role in fostering peace and stability in the region."}
{"p": "\u201cKenya is a powerhouse in the Horn of Africa in terms of peace and security. We appreciate the important role Kenya has continued to play\u00a0in this endeavor,\u201d Xue said."}
{"p": "Xue, who paid a courtesy call to the\u00a0State House\u00a0in\u00a0Nairobi, said China has come up with a proposal to hold a conference that will bring together all countries in the region to discuss peace and development."}
{"p": "The conference,\u00a0to be held in the first half of the year,\u00a0is expected to offer a platform for countries in the region to settle their differences through negotiation."}
{"p": "Kenyan President Uhuru Kenyatta assured Xue of Kenya\u2019s readiness to work with China and other stakeholders in support of regional peace and prosperity."}
{"p": "\u201cYou can count on us as dependable allies and partners in the efforts to bring peace, stability and prosperity in the region. We are doing this because we know a peaceful and stable Horn of Africa region means a peaceful\u00a0and stable Kenya,\u201d Kenyatta said."}
{"p": "They called on parties involved in conflicts in Ethiopia, Sudan, South Sudan and Somalia to embrace dialogue as the best way of resolving their differences."}
{"p": "They also applauded the enhanced bilateral ties between Kenya and China that have seen the two countries strengthen their cooperation both at the bilateral and multilateral levels for the benefit of their citizens."}
{"p": "Free movement of people should be reinforced in Africa to boost economic integration of the continent for common prosperity, according to a report released by the African Union last week."}
{"p": "Despite aspirations of African nations to foster closer connections to facilitate trade, lower transaction costs and improve production efficiency, many obstacles still hinder integration within the continent, such as strict restriction of intracontinental movement, stated the 2021 African Integration Report: Putting Free Movement of Persons at the Center of Continental Integration."}
{"p": "In addition to the free movement of people, free movement of goods, services and capital are also essential for African integration and should be collectively reinforced."}
{"p": "The report stated that the level of integration on the continent is low overall, and one of the biggest impediments to promoting trade within Africa is the visa requirements between member states."}
{"p": "\"There is great disparity in countries' scores on the Free Movement of People dimension. Many countries still have roadblocks that African citizens encounter when they travel. Adhesion to the Free Movement of Persons Protocol and greater visa openness would improve scores on this dimension by lowering transaction costs, increasing trade and making production more efficient,\" the report stated."}
{"p": "Comoros, Djibouti and Somalia share the top position on the free movement of people dimension, while countries including Libya, Eritrea, Ethiopia and Burundi are the least integrated countries on the free movement dimension and most African citizens need a visa to enter their territory."}
{"p": "Philomena Apiko, who heads AU-EU relations at think tank European Centre for Development Policy Management, said despite low scores, many African countries have had strong desires for African integration since decades ago."}
{"p": "\"This aspiration is implicitly included in the AU's 'Agenda 2063: The Africa We Want', which cites the desire of African Union member states to move toward shared prosperity and well-being, to achieve a prosperous Africa based on inclusive growth and sustainable development. This is a desire for an integrated continent, politically united and based on the ideals of Pan-Africanism and the vision of African Renaissance,\" Apiko said."}
{"p": "However, based on her research, Apiko said AU member states which have ratified the African Continental Free Trade Area, or AfCFTA, and those who have ratified the AU Free Movement Protocol will still need to make changes to their national laws and regulations to allow migrants including business persons and workers to access their domestic labor markets."}
{"p": "\"The main challenges come with the changes required to ensure that nationals and other African migrants have the same rights and access to services. This may be difficult, even for those member states who are part of regional economic communities' free movement protocols, despite their advancements in promoting labor mobility,\" she said."}
{"p": "Africa has one of the world's highest visa requirements. This situation is even more restricted for Africans traveling within Africa. Only five African countries, namely Seychelles, Mozambique, Rwanda, Comoros and Madagascar, offer visa-free access or visas on arrival to citizens of all African countries."}
{"p": "In addition to encouraging the free movement of people, Apiko said the interface between the AfCFTA and regional economic communities and customs unions should be recognized as critical to the successful implementation of African integration."}
{"p": "On Thursday night, Kempinski Hotel Changsha successfully held a\"Bach & Baroque\" charity concertini, a new concert offering a fresh interpretation on compositions from centuries ago. Pianists Wang Xiaofan and Zhou Jingjia jointly performed a brilliant repertoire of Bach classics. They worked together on a vivid display of Baroque music, complex melodies and rhythmic sophistication."}
{"p": "\"Kempinski Hotel Changsha is the first Kempinski hotel within the group globally to host this concertini, which melts love into notes and movements,\" said general manager Michael Tan. \"It's a very special concert. Bach's music is often labeled 'sensible', though it actually has an emotional side. I hope guests feel something as they leave the concert.\""}
{"p": "At the moment, as classical music has a growing audience and is gaining more popularity among young people, this music strikes a particularly valuable chord. \"Tonight at Kempinski, music-lovers enjoying Bach's timeless classics can perceive the beauty and style of freedom in the divinity of music, and witness a spiritual gathering across time and space,\" Tan added."}
{"p": "\"2021's concertini is a very special event. It brings European culture, music, art and food to Changsha and gives us the opportunity to spend a wonderful evening together while enjoying classical music, gourmet food and performancesthrough the night,\" said Zhan Miao, general manager of Changsha Concert Hall."}
{"p": "In order to create a new generation of passionate and cultured music lovers who will cherish and support great music forever, Kempinski Hotel Changsha raised funds at the event and donated 40,000 yuan to the Xin Xin Public Welfare Organization for children in need."}
{"p": "Hotels are introducing programs aimed at healing the body and mind to appeal to health-conscious guests and those looking to boost their energy levels."}
{"p": "Typically a lifestyle observed by middle-aged or older people, yangsheng has gained popularity among younger Chinese in recent years."}
{"p": "Yangsheng, or nurturing life, is a core component of traditional Chinese medicine that places paramount emphasis on the prevention of illness and fostering health and well-being."}
{"p": "In a survey of Generation Z-people born between the mid-1990s and the early 2010s-conducted by Beijing-based financial information provider Rong360, 91.6 percent of respondents considered physical health the most important thing in life."}
{"p": "Growing stress from life and work is one of the reasons why people are seeking more ways to rejuvenate themselves."}
{"p": "In an online survey polling 1,000 participants conducted by Shanghai-based consultancy CBNData in June 2021, 59 percent said they had experienced work-induced pressure and anxiety in the past year. Fifty percent of 962 respondents said they would participate in healing activities, such as massage and yoga, to relieve stress."}
{"p": "The increased interest in wellness is driving changes in the hotel industry."}
{"p": "\"Changes in society and the COVID-19 pandemic have greatly altered people's attitudes toward health,\"Tang Min, general manager of the Six Senses Qing Cheng Mountain hotel in Southwest China's Sichuan province, told Jing Daily, a digital publication that focuses on luxury culture and lifestyles in China."}
{"p": "\"People are more eager to establish contact with themselves, others and nature. Generally, they hope that when their trip is over, they can live better than before,\" she said."}
{"p": "For the hotel industry as a whole, she said the era of hotels only providing beds and meals is becoming a thing of the past."}
{"p": "\"Hotels today are more focused on the guest experience,\" she said, adding that staying in a wellness hotel is a healthy experience that allows people to relax physically and mentally, change themselves and become a positive influence to people around them."}
{"p": "The quality of sleep is arguably one of the most important determinants of good health."}
{"p": "This opinion is shared by the majority of the respondents to a survey cited by CBNData. It showed that 81 percent of those polled considered \"sleeping well\" part of the definition of \"healthy\"."}
{"p": "An increased need to improve the quality of sleep has presented new opportunities to hotels where many guests sleep in."}
{"p": "In January, Rosewood Hotels &Resorts introduced Alchemy of Sleep, a collection of immersive retreats designed to promote rest through sleep-inducing treatments, movement-driven activities and special amenities."}
{"p": "Included in the package are 60-minute rejuvenating body treatments, 90-minute relaxing spa treatments and a daily restorative breakfast."}
{"p": "Kimpton Hotels & Restaurants, a brand owned by InterContinental Hotels Group, announced in February a partnership with Talkspace, an online behavioral health company, offering mental health services to guests as well as employees."}
{"p": "But, can any hotel with a wellness program, a healthy menu, a spa and a gym call itself a wellness hotel?"}
{"p": "The answer is no according to an article by the Ganyong hotel research institute published on meadin.com, a commercial property information provider."}
{"p": "A wellness hotel, the article suggests, must have the concept of wellness embedded into its DNA, philosophy, culture, system and services."}
{"p": "Its services must start before check-in and cover the cycle from disease prevention, detection and treatment to rehabilitation and health management. Services such as screening tests for serious diseases, genetic testing and private medical consultation should be offered."}
{"p": "Moreover, a wellness hotel should provide care for the guest's body, mind and spirit, and try to foster a harmonious relationship among nature, space, people and services, according to the article."}
{"p": "Looking into the future, Tang Min with Six Senses Qing Cheng Mountain told Jing Daily that the concept of sustainable development will be a major trend in the wellness hotel industry."}
{"p": "Sustainability in personal health and that in the natural world are expected to complement and exert a positive influence on each other, she noted."}
{"p": "The fifth wave of COVID-19 infections in the Hong Kong Special Administrative Region has created new challenges for the city's prevention and control system and its ability to appropriately respond to the public health crisis."}
{"p": "Hong Kong's prevention and control mechanism is different from that of the Chinese mainland. However, the failure to contain the spread of the novel coronavirus will pose a serious threat to the health and livelihoods of local residents, especially vulnerable groups such as the elderly and children."}
{"p": "Previously, Hong Kong made concerted efforts to contain the pandemic, with the central government only providing materials and personnel to the SAR government, as the anti-pandemic measures were initially regarded as a matter within the scope of Hong Kong's self-governance."}
{"p": "But the fifth wave of infections has been threatening the lives, health and safety of every Hong Kong resident, and undermining the city's prosperity and stability and the country's policy of integrating the city into its overall development plan. Therefore, the central government has to come to Hong Kong's aid in accordance with the Basic Law of the Hong Kong SAR."}
{"p": "The State's support for Hong Kong to fight the pandemic is for the greater good of the city and the country."}
{"p": "To begin with, the central leadership's instruction on how Hong Kong should effectively contain the outbreak is part of a national mission. While the SAR government takes the primary responsibility of containing the spread of the virus in the city, the central authorities and some departments in neighboring provinces will help the Hong Kong officials in their endeavor."}
{"p": "Second, an efficient and timely supply of daily necessities and medical resources and staff from the mainland has plugged the loopholes in the SAR's anti-pandemic system in a short time, significantly boosting the city's confidence in containing the virus."}
{"p": "Third, some of the mainland's effective measures to contain the pandemic have been applied in Hong Kong including mass testing, rapid construction of makeshift hospitals, and mobilization of people from different sectors in the fight against the virus. And the SAR has promulgated anti-pandemic rules according to the emergency law."}
{"p": "Thanks to the cooperation among the authorities, Hong Kong has adopted measures that suit local conditions and, unlike some Western economies, ruled out the idea of living with the virus or blindly copying anti-pandemic measures from mainland cities."}
{"p": "The city's health authorities are taking all infected residents into consideration and focusing on providing them fast and effective treatment, in order to reduce the fatality rate. While patients with mild symptoms are being treated in makeshift hospitals or being asked to quarantine themselves at home, those with serious symptoms are getting specialized treatment in established hospitals."}
{"p": "And since such measures have proved effective, an increasing number of Hong Kong residents are supporting the strict approach to fighting the virus."}
{"p": "In short, although Hong Kong, with more than 1 million infections and about 6,000 deaths in this wave, has had a hard time combating the virus, it can now hope to contain the epidemic with the support of the central government."}
{"p": "With the mainland's support, Hong Kong is capable of overcoming all difficulties and challenges and returning to the road to prosperity and stability. The central government's support to Hong Kong shows not just the advantage of \"one country, two systems\" but also the strong sense of responsibility of the country's leadership when it comes to safeguarding the health and life of people across the Chinese nation."}
{"p": "There is no conclusive evidence to prove Chinese people are reading fewer books nowadays. Those who say people are reading \"fewer books\" cite this year's survey which shows that on average, a Chinese adult reads only 4.7 paper books in 2019, a sharp decline compared with previous years."}
{"p": "Even if we add the number of e-books, the total number of books an average Chinese citizen reads is still about eight, far fewer than their German and Japan counterparts who read at least twice as many books."}
{"p": "On the other hand, those who claim the Chinese people are reading \"more books\" argue that instead of paper books, people are reading books and other materials on computers and smartphones because of the change in reading habits. To prove their point, they say the number of online literature readers in China has increased to 460 million and that the authorities have asked schools to reduce homework because primary and high school students were spending too much time on reading books."}
{"p": "But the fact is, younger people today read less as compared with my generation because they have other engagements and sources of recreation\uff0dattending after-school courses, playing electronic games, or attending interest group gatherings or parties."}
{"p": "Such activities were unheard of in the 1960s and 1970s, so people found refuge in books. Unable to afford expensive novels, we borrowed them either from libraries or from friends. And whenever we found a classic such as the Romance of the Three Kingdoms or The Three Musketeers\uff0dwhich were banned during the special period in the 1960s and 1970s\uff0dwe finished reading them in one or two days before passing them down to the next waiting borrower."}
{"p": "When the ban on such books was eventually lifted after the launch of reform and opening-up four decades ago, people were thirsty for good books and the reprinted classics, both Chinese and Western, were sold out fast."}
{"p": "Since then the central and local governments have been encouraging reading. Apart from earmarking Sept 28, Confucius's birthday, as the National Reading Day, China has also built cultural service centers in most of its administrative villages, which usually have reading rooms and a good collection of books, magazines and newspapers, as well as computers."}
{"p": "The government runs 3,196 public libraries which have a collection of more than 1.1 billion paper books, 866 million e-books and 225,000 computers. But despite these efforts, people borrowed only 541 million books from libraries last year, a sharp decline of 39.3 percent year-on-year."}
{"p": "While the strict pandemic prevention and control measures were partly responsible for the decline in book borrowing, the fact that an increasing number of readers, especially the young, are using computers and smartphones to read books and other contents should not be disregarded."}
{"p": "A survey of people's reading habits conducted in 2021 showed that on average 51.8 percent of the people spend at least half an hour each day reading contents online. The younger the reader, the higher the percentage and longer the time they spend online."}
{"p": "This phenomenon is worrying not only parents and educators but also health workers. Doctors have warned that spending too much time glued to a smartphone or computer screen could be harmful to people's health. Data from the national health authority show 35.6 percent of primary school students, 71.1 percent of junior high school students and 80.5 percent of senior high school students suffer from myopia."}
{"p": "Also, when children spend a lot of time on their smartphones, it is difficult for their parents to know whether they are reading serious works, or sensational reports, disturbing stories or just playing computer games, which are harmful."}
{"p": "Website publications are usually not well edited and their language quality leaves much to be desired and their perspective on life is not necessarily positive, many educators say."}
{"p": "But since the change in reading habits is an irreversible trend, the authorities in charge of monitoring online content have an urgent task to fulfill: of ensuring that at least the publications on the online reading platforms are of good quality and healthy."}
{"p": "The United States, the European Union and several other economies have imposed several rounds of economic sanctions on Russia over the past weeks in order to punish the country for its actions in Ukraine."}
{"p": "This is despite the fact that economic sanctions have, in the past, failed to achieve their goals, as in evident in the cases of Iran, Syria, the Democratic People's Republic of Korea, Venezuela and Cuba, which are the most sanctioned countries by the US and its Western allies. The sanctions have, however, led to huge suffering of ordinary people in those countries, in particular women and children."}
{"p": "I have visited Cuba three times and seen for myself the horrible human sufferings caused by the US embargo of the small island country since the early 1960s, a brutal embargo that has been overwhelmingly condemned by the United Nations General Assembly every year for the past three decades."}
{"p": "In their latest rounds of sanctions on Russia, US and EU leaders have naively assumed that their severe sanctions will cripple the Russian economy, thereby forcing the population to revolt against the government. But nothing like this has happened in the past. What we have witnessed were often to the contrary: The local population tended to rally even more closely around its government and leaders to resist bullying by foreign powers."}
{"p": "It is therefore shocking to hear Western government leaders and politicians bragging about how their harsh sanctions have destroyed a country's economy, such as causing currency depreciation and price hikes. It literally means they don't care about the sufferings of millions of ordinary people."}
{"p": "In a globalized world, economic sanctions often mean huge disruptions in global supply chains, which make those sanctions a collective punishment for the entire world, especially the poor countries."}
{"p": "Instead of easing the tensions, economic sanctions tend to escalate them, as well as intensify hostilities, and make it even more difficult to resolve conflicts through peaceful talks."}
{"p": "Unlike sanctions endorsed by the United Nations Security Council, unilateral economic sanctions imposed by the US and its Western allies totally lack international legitimacy. This is especially true for the US which has been recklessly abusing its economic, financial and military might to sanction dozens of countries, including on China."}
{"p": "In the past, the US also threatened to sanction EU companies which conducted normal trade with Iran after the Donald Trump administration pulled out of the Joint Comprehensive Plan of Action, popularly known as the Iran nuclear deal, in 2018 and re-imposed sanctions on Teheran. The EU protested against the move and later and devised the INSTEX financial tool to help its companies bypass US sanctions."}
{"p": "The US is again threatening sovereign countries, those that have normal economic and trade relations with Russia, and forcing them to choose sides. It is again warning countries in the same absurd way that former US president George W. Bush did to justify his devastating wars in Afghanistan and Iraq \u2014 \"you are either with us or with the terrorists\"."}
{"p": "If the US is allowed to punish other sovereign countries which maintain normal trade relations with Russia, then the international rules and the world order will indeed have to be rewritten and replaced by power politics."}
{"p": "When I raised such questions at the European Commission's daily briefing on Tuesday, the spokesman said the EU's economic sanctions against Russia do not have extraterritoriality. But he wouldn't comment on the US sanctions which do have extraterritorial dimensions."}
{"p": "Economic sanctions have long proved to be ineffective in conflict resolution. Peaceful dialogues, which China has been calling for given its good relations with both Russia and Ukraine, are a better way of resolving the current crisis."}
{"p": "With the number of COVID-19 cases rising in major cities, China is facing the most serious wave of sporadic outbreaks since the lockdown of Wuhan was lifted in April 2020."}
{"p": "The resurgence of infections has underscored, once again, why it is important for China to adhere to its dynamic clearing policy which, instead of trying to realize zero-infection, is aimed at stamping out local outbreaks through early detection, swift response, targeted containment and effective treatment."}
{"p": "The highly transmissible and insidious nature of the Omicron variant of the novel coronavirus requires the government and the public to react even more quickly to any signs or symptoms of infection, in order to halt the spread of the virus and prevent the medical system from being overstretched and the death toll from increasing. As a country with a population of more than 1.4 billion, of which more than 18 percent are aged 60 or above, China cannot afford to let its guard down, because that could lead to many deaths."}
{"p": "The Chinese government prioritizes human life. And the pandemic has prompted it to make greater efforts to safeguard human health and life. Indeed, it was due to its effective prevention and control measures that China hosted a \"simple, safe and splendid\" Beijing 2022 Winter Olympic and Paralympic Games in February-March. The closed-loop system introduced in late January helped maintain the infection rate at the Winter Olympics at just 0.01 percent, an incredible feat which was lauded by the International Olympic Committee and sports federations around the world."}
{"p": "To ensure the success of the national campaign to stamp out new outbreaks, local governments are required to rigorously follow the mass testing, quarantine and treatment protocols. However, these strict control and prevention measures must be implemented and targeted in a way that causes the least inconvenience to residents."}
{"p": "There is also a need to find more sustainable ways to address the challenge, including by providing home test kits and antiviral pills for residents, and further strengthening healthcare services so they can deal with bigger emergencies. Fortunately, the national health authority announced recently that five COVID-19 antigen test kits can be used as a supplementary diagnosis tools to the nucleic acid test to improve early detection capability."}
{"p": "The public has been complying with the anti-pandemic strategy, strictly following the prevention and control measures, for example, by scanning the health code before visiting facilities such as malls, supermarkets and restaurants, as well as wearing face masks, and maintaining social distancing."}
{"p": "In the cities witnessing a resurgence in cases, people have been cooperating with the government by undergoing mass nucleic acid tests and welcoming closed-loop management for residential communities."}
{"p": "The authorities believe that protecting people's lives and promoting economic development are mutually reinforcing. In fact, China's policy to coordinate pandemic control measures with economic growth activities is best suited to the country's real conditions and most beneficial to the world. For example, by keeping the numbers of infections and deaths extremely low, compared with other countries, China has helped keep the global supply chains running despite the obvious disruptions."}
{"p": "Also, China was the only major economy to achieve positive growth in 2020\uff0dand rebound strongly with 8.1 percent growth in 2021. And China's GDP growth was better than expected in the first two months of this year, which bodes well for its steady recovery in the first quarter."}
{"p": "To be sure, China has a good chance of keeping its growth within a reasonable range in 2022, according to analysts. But the analysts have also warned that the Chinese economy faces new downward pressures due to the fluid global environment and the pandemic. So we can expect more supportive fiscal and monetary policies to achieve the annual growth target of around 5.5 percent."}
{"p": "China's top leadership has stressed the need to coordinate COVID-19 prevention and control measures with economic and social development, and accord increasing importance to ensuring steady growth."}
{"p": "Acknowledging that the economy faces new challenges, including downward pressure, the government has reiterated that it will make more efforts to boost domestic demand, unleash consumption potential and increase investment, and introduce tax refunds and cuts to maintain stable macroeconomic performance."}
{"p": "All these indicate that it is difficult to maintain normal economic activities amid strict anti-pandemic measures, but China has to navigate the choppy seas to achieve high-quality economic development and maintain its global competitiveness."}
{"p": "\u00a0"}
{"p": "\u00a0"}
{"p": "On Feb 24, Russian President Vladimir Putin denounced the West for three decades of broken pledges and NATO's expansion, vowing to \"demilitarize and denazify\" Ukraine and ordering a \"special military operation\". In the West, the speech was portrayed as a conspiracy fantasy."}
{"p": "Yet declassified documents show that several US and European leaders did give security assurances against NATO's eastward expansion at the turn of the 1990s. These pledges were posted online by the Washington-based National Security Archive in 2017."}
{"p": "Moreover, NATO's expansion was widely condemned in 1997 by 50 leading US foreign policy experts. Recently, one of those experts, Michael Mandelbaum, called it \"one of the greatest blunders in the history of American foreign policy\". And yet, as in 2014, the friction is being promoted by the US leadership, which has also supported far-right extremists whom Ukrainian people in general shun."}
{"p": "The blueprint comes from a 2019 report by RAND Corporation, US defense contractors' prime think tank, which outlined the steps for maximum sanctions. Ukraine is the means. The goal is to debilitate the Russian economy, by default. The consequent impairment of the world economy is seen as collateral damage."}
{"p": "By contrast, China, right from the beginning, has called for talks to end the deadly conflict, while urging \"maximum restraint\" and \"de-escalation\"."}
{"p": "Despite promises to the contrary, the Biden administration's sanctions have been designed to cause extensive harm to the Russian economy and its people. As a net consequence, the global economy \"could soon be faced with one of the largest energy supply shocks ever\", as Goldman Sachs has warned."}
{"p": "Due to the central role of both Russia and Ukraine in the global agricultural markets, the United Nations has warned that the world is facing a meltdown of the global food system."}
{"p": "As for China, some of the Chinese government's key investment areas focus on food and energy security. \"It is important to fill the rice bowl of Chinese people, mainly with Chinese grain,\" as President Xi Jinping recently said."}
{"p": "Last year, more than half of China's energy imports was crude oil. The oil and natural gas imports are diversified, so losses could be offset in part by cheaper imports from Russia, China's second-largest oil supplier."}
{"p": "Besides, Beijing and Moscow recently signed a new 30-year natural gas contract. And Saudi Arabia, China's largest source of oil, is considering accepting payments in the Chinese currency, instead of US dollar, for some oil purchases. As the yuan has strengthened from about 7.18 in June 2020 to about 6.35 to a US dollar, the appreciation will allow China to also secure the imports of other commodities at lower costs."}
{"p": "Before March, China's economic performance indicated stabilization thanks to export-led industrial expansion and rising global demand. Similarly, retail sales rebounded, including for more expensive items, as well as cars."}
{"p": "On the supply side, the government's fiscal spending and infrastructure investment have, in turn, boosted fixed asset investment. And since property market policies have been adjusted, the construction of pre-sold homes may be completed with the support of new purchases."}
{"p": "However, headwinds have gained pace since late February. After Hong Kong, COVID-19 infections have been reported in more than 100 Chinese mainland cities including Shenzhen, Guangdong province, and Shanghai, prompting authorities to implement stricter anti-pandemic measures. As factories in Guangdong, for example, account for a fourth of China's exports, the authorities have been compelled to implement such measures to contain the spread of the virus, in order to prevent any further disruptions in supply."}
{"p": "The Government Work Report, submitted by Premier Li Keqiang during the annual session of the National People's Congress early this month, says the government will provide strong support for the economy and boost fiscal spending. Also, the report has set 5.5 percent as the new GDP growth target for 2022 and said the government also aims to create more than 11 million new jobs in the year."}
{"p": "The longer the Ukraine crisis and the pandemic last, the more adverse will be their impact on global economic prospects. With the Ukraine crisis and its likely prolonged aftermath, the consequent headwinds, coupled with 10 percent inflation and aggressive rate hikes, will penalize US recovery. And a protracted impact would be particularly painful for Europe, which is pushed to pay the primary bill for the misguided geopolitics."}
{"p": "In the West, economic sanctions have been projected as a solution to the Ukraine crisis with minimal harm to the world economy. In reality, the sanctions will prolong the conflict and amplify global economic risks."}
{"p": "First, Russia is no Afghanistan. Its $1.8 trillion economy is the world's 11th largest. It is a global supplier of oil and natural gas, and a leading nuclear power."}
{"p": "Second, thanks to US protectionism and trade wars since 2017, global recovery has been undermined, which makes stagflation in the West a self-induced calamity."}
{"p": "Third, in the absence of enduring peace, protracted sanctions, following the pandemic-induced economic depression, could cause more lost years in the West and lost decades in many developing economies."}
{"p": "Fourth, a new Cold War and NATO's further expansion will steer fiscal packages away from welfare and security, where they are most needed, toward rearmament drives that benefit mainly the Pentagon's big defense contractors."}
{"p": "And fifth, as the US Federal Reserve has begun its aggressive round of rate hikes, it will accelerate economic shocks. In India, for instance, fleeing foreign investors have already sold more equities than during the 2008 global financial crisis."}
{"p": "Together, these factors will penalize global growth prospects. In fact, fuelled by rising downside risks, the world economy is indeed too close to the edge."}
{"p": "\u00a0"}
{"p": "China's emergence as a world leader in solar, wind, hydroelectric and geothermal power generation makes it a natural Argentina ally. Over the years, the country's government and corporations have attracted Chinese investment and finance into renewable and other types of energy sectors to accelerate Buenos Aires' sustainable economic development and hybrid pathway."}
{"p": "With Chinese investments and technological assistance, Argentina had built one of Latin America's largest solar energy plants, Cauchari Solar Park, in Jujuy. The world's highest altitude facility provided power to 160,000 families and turned into a poverty alleviation and social welfare effort when it hired local residents after providing technical training, and was projected to generate $400 million in net profits for the province, widening fiscal space for establishing new schools."}
{"p": "Beijing's comprehensive strategic partnerships with Argentina and other regional states, mostly in the energy sector and infrastructure development, as well as the induction of 21 Latin American countries into BRI, however, are unsettling lawmakers in Washington. Skepticism about China's\u00a0growing economic relationship with\u00a0the region has been aggravated by Donald Trump's antipathy toward China's economic and technological rise and is being continued by US President Joe Biden's spendthrift policy."}
{"p": "In December, US Congress completed action on the National Defense Authorization Act, creating a provision for a report by June 30 on Chinese efforts to expand \"presence and influence\" in LAC. Wary of Chinese infrastructure investments in the region, the US House and Senate in June 2021 and February 2022 approved broad bills to compete with China worldwide and bolster America's economic competitiveness to regain US dominance in LAC."}
{"p": "Citing so-called national security threats, US legislators even introduced a bipartisan bill, \"Western Hemisphere Security Strategy Act of 2022,\" to undermine the China-LAC relationship. But concerns about alleged China's expanding security footprint in LAC are being snubbed by regional academics who dub the claim a \"rich-world problem.\" What's more, the regional countries don't see Chinese investments in Argentina as a \"zero-sum game\"."}
{"p": "Argentina itself has been keenly interested in expanding currency cooperation and becoming part of the BRI family. The \"strategic decision\" of joining the Chinese intercontinental project and extension of \"monetary swap\", an Argentinean official said, will guarantee finances or investments of more than $23.7 billion and bolster the dwindling forex reserves."}
{"p": "The bilateral consensuses reached between Chinese and Argentinean leadership at a Beijing summit, as the two countries celebrate the 50th anniversary of diplomatic ties this year, should set the stage for collaboration in trade, infrastructure, anti-pandemic cooperation, digital economy and green development as well as taking the diplomatic and political relationship to new heights."}
{"p": "President Alberto Fernandez's move will further help Argentina \"diversify the range and possible destinations\" of its exports to China and other BRI countries. After years of diplomatic neglect, the Biden administration last year mooted Build Back Better World in LAC. Yet Buenos Aires, holding the high diplomatic status of \"strategic integral alliance\" from Beijing, threw its weight behind BRI."}
{"p": "Argentina's affiliation with BRI would expand energy deals between the two countries, boosting the former's wind and solar sectors. It additionally offers an opportunity for the South American economy to make its pie bigger in China-Latin America trade, which has risen to $451 billion at a staggering increase of more than 40% in 2021."}
{"p": "Experts called for greater cooperation between China and Argentina on transmission infrastructure. While Beijing plans to modernize some of the country's outdated transmission infrastructure as Buenos Aires is in talks with Chinese firms, these investments and other infrastructure projects will likely increase under BRI to boost Argentina's socio-economic development."}
{"p": "Argentina's decision to accede to BRI is its legitimate and sovereign right and shouldn't be used as a tool for the US to undermine the cooperation. Integration of LAC's third-largest economy into the trillion-dollar roster doesn't challenge or pose a threat to any doctrine or American security. This bullying and assertiveness, to impede cooperation between two sides or impede growth of either of the two, cannot survive in a free and multilateral world and must be ceased."}
{"p": "The 2022 Winter Paralympics, after 10 days and 78 events, officially came to an end Sunday night at Beijing National Stadium. One legacy greater than the stunning total of 61 medals won by China \u2013 18 golds, 20 silvers, and 23 bronzes \u2013 is the seed of an accessible society in all respects for people living with disabilities."}
{"p": "Efforts to build a barrier-free environment for both the Paralympics athletes and spectators date back to 2016, when the Beijing 2022 Organizing Committee started working on the first draft of The Guide to Barrier-Free Services, just one year after the capital of China was selected as the host city. In 2018, The Guide was released, upholding the basic principles of \"fairness, dignity, and suitability\"."}
{"p": "In 2020, Beijing Institute of Architectural Design issued illustrative, specific instructions to build accessible competition venues, stadiums, Paralympics-related public spaces, and other facilities. By the end of 2021, with nearly 150,000 spots upgraded, key areas for the Games in Beijing were declared barrier-free, according to Beijing Daily."}
{"p": "Eventually, inclusivity, care, and respect for people with disabilities were woven into every little detail of the Games. At Beijing National Aquatics Center, a Z-shaped accessible lane, which was 80 meters long and 2 meters wide, made its way to the ice rink; accessible seats were set up for spectators with disabilities and their companions; extra-wide temperature measuring doors were friendly to wheelchair users. In the Paralympics villages, LED lights and curtains could be controlled via smartphones; athletes could handle L-shaped doorknobs in both sitting and standing positions; toilets and shower rooms were equipped with grab bars. Also, volunteers would offer help only when it was requested."}
{"p": "The accessible facilities were highly praised by our international friends. IPC accessibility specialist Ileana Rodriguez said Beijing has set a high bar on accessibility for future Paralympics. American Paralympic ice hockey athlete Kyle Zych told Xinhua News Agency he felt \"so lucky to experience such an amazing village and venue\". Netherlands coach Nicky Elsewaerd commented that the facilities here were the best of the last three games."}
{"p": "Liu Xinghua, head of the committee's legacy office, says the Games and its preparation have left a profound legacy, providing a new beginning to build a more inclusive society where people with disabilities can enjoy a richer life."}
{"p": "Currently, in China, approximately 85 million people are living with disabilities, according to the China Disabled Persons' Federation. The total number is estimated to reach 100 million in 2030."}
{"p": "Steady progress has been made to ensure the full and equal participation of people with disabilities in Chinese society, especially after the reform and opening-up policy was launched in 1978. Notably, in 1982, the protection of citizens with disabilities was written into the Constitution of the People's Republic of China. In 1987, the first national sample survey on disability was conducted. Since the turn of the 21st century, the focus shifted from social welfare to a wide range of issues including barrier-free environment, social security, and poverty alleviation."}
{"p": "According to an official report, the survival and security index for persons with disabilities rose to 75 percent in 2018. But the most remarkable achievement is in sports: China ranked first at the medal tables for both the 2020 Summer Paralympics and the 2022 Winter Paralympics, claiming 96 and 18 golds, respectively."}
{"p": "What's next? As China steps into a new era, its people and leadership are calling for greater accessibility for individuals with disabilities not just at the Paralympics, but in every fabric of society \u2013 from special education to fulfilling employment, from better rehabilitation services to more affordable medical insurance."}
{"p": "The Paralympic flame was extinguished in the closing ceremony. But the fire in our heart has been ignited. Standing on the solid ground of moderate prosperity, we now have the privilege to build an accessible society in all respects where disabilities are no longer a hindrance to greatness but a normal part of our day-to-day life accommodated by an egalitarian ideal of love and respect. This is our Chinese dream, a dream for everyone."}
{"p": "The relationship between China and Arab states dates back to antiquity. More than two thousand years ago, land and maritime Silk Roads connected the two ancient civilizations and fastened them in affinity. The discovery of the primitive port of Jeddah in 2018 during a 20-day Chinese-Saudi joint excavating mission of the ruins of al-Serrian established these historical interactions."}
{"p": "Since the unveiling of Saudi Vision 2030, Beijing has expressed a willingness to help Riyadh chart a new path of economic diversification and synergize the Belt and Road Initiative (BRI), which the Kingdom has already signed up for. The Saudis' strategic framework aims to reduce dependence on oil and transform the Kingdom into a leading industrial powerhouse and global trading and logistics hub."}
{"p": "Mutual interests, the complementary nature of these initiatives and mercurial regional strategic landscape over the last few years have led to expansion in the Saudi-China relationship. The internally conflicted US policy, to limit American engagement in the Middle East and bully the regional allies to choose between Beijing and Washington, has dismayed Saudi Arabia, urging it to benefit from China's growth, enormous market and investment capability."}
{"p": "Riyadh is positioned at the nexus of the East and West, raising the profile to become an epicenter of international trade. This ambitious goal, given building a regionally competitive and sustainable maritime industry is one of the key Saudi objectives, comfortably meshes with China's ocean-going 21st Century Maritime Silk Road and seeks broad-based cooperation with the world's second-largest economy."}
{"p": "In December, King Abdulaziz Port in Dammam was included in the newly launched China Service to ensure direct and efficient connectivity for importers and exporters in the country and region with China. The initiative, aimed at enhancing competitiveness of the port and increasing trade between the two countries, will inevitably shore up maritime links and further build nation-to-nation relations."}
{"p": "Chinese and Saudi firms recently signed a memorandum of understanding (MOU) in innovative space technologies, satellites, artificial intelligence (AI) and geospatial products that would support Saudi strategic space and geospatial industry, and marks a major step forward to realize the country's futuristic ambitions."}
{"p": "Cooperation between China and Saudi Arabia continues to strengthen as Saudi state-owned oil company, Aramco, took the \"final investment decision\" to develop a refinery and petrochemical complex in Northeast China. The vision to create a modern economy and shared challenge of energy security made Beijing the bedrock of the oil conglomerate's downstream expansion strategy in Asia and turn it into a leader in the global liquid-to-chemical industry."}
{"p": "The deal \u2013 which is subject to regulatory approvals and will combine 300,000 barrels per day refinery capacity and ethylene-based steam cracker, a building block petrochemical used to manufacture thousands of everyday products \u2013 is the latest example of China-Saudi strategic cooperation. The negotiations, reportedly resumed in February, underscored the Kingdom's \"extremely significant shift\" from the US to China and described Riyadh's proclivity to better align itself in a fast-changing geopolitical reconfiguration."}
{"p": "In yet another sign of broadening strategic relations, the Saudi Digital Academy last month signed an MOU with Huawei. The consent is intended to sponsor and develop 8,000 local technology talents and will contribute to Riyadh's digital transformation under the Vision. The Chinese tech giant would also coach 100 Saudi trainers on crucial technologies including AI, cloud computing, cybersecurity and 5G uses to provide the Kingdom with future tech leaders."}
{"p": "Riyadh was Beijing's top crude oil supplier in 2021. After replacing the European Union as the largest trading partner of the Gulf Cooperation Council in 2020, China is playing an important role in the development of Saudi and the region's non-oil sector too, such as tourism, telecommunications, smart cities and renewables, among other technology-driven industries. The burgeoning trade as well as a strong compatibility in other sectors has augmented the bloc's general perception about Beijing and eminence as a top strategic ally, paving the way for enhanced engagement."}
{"p": "Over the years, China and Saudi Arabia have steadily matured their trade relationship into intimate friendly collaboration and comprehensive strategic partnership. It is, however, critical not to pair the evolution of bilateral cooperation, based on reciprocity and mutual understanding, with either country's dealings with the US and other states. Such a balanced and pragmatic approach would accelerate each other's growth ambitions and open up new vistas for economic diversification."}
{"p": "\u00a0"}
{"p": "Nowadays, nearly nobody would question the continuous and rapid economic growth of China in the past four decades. But many people, including Chinese and foreign scholars, think that the financial development in China is at a low level. This China Puzzle seems contradictory to the well-accepted view that financial development and economic growth always go hand in hand."}
{"p": "The China Puzzle is mainly due to the direct or inappropriate application of Western economic theories or measures to China with the unique cultural, economic and institutional environment. For example, the level of financial development is commonly measured by the ratio of credit extended to the private sector through banks and financial markets to GDP (gross domestic product). This measure would underestimate the level of financial development in China, as multiple forms of ownership coexist with State ownership as the mainstay in China."}
{"p": "In the United States, today's mainstream ideology believes that private ownership and market mechanism are more efficient, and thus private ownership should be preferred to public ownership. Therefore, private ownership is prevalent in all sectors of the US economy. In the US, private jails, prisons, and detention centers are common. Even the US central bank-the Federal Reserve System, is a cooperative of private banks, and not to mention other industries."}
{"p": "Consequently, the private sector accounts for the largest portion of the US economy with the absolute majority of contributions to the GDP of the US. Therefore, it is natural that the ratio of credit extended to the private sector through banks and financial markets to GDP in the US would be high or the measurement correctly reflects the level of financial development in the US. Moreover, financial development and economic growth are closely (positively) correlated in the US."}
{"p": "In China with different economic and institutional environment, State ownership is one of the main pillars of the economy. Side by side with the rapid development of private enterprises, State-owned (or controlled) enterprises contribute as high as 40 percent of the GDP in China."}
{"p": "Although the financial systems in China develop normally and facilitate the economic growth successfully, the ratio of credit extended to the private sector through banks and financial markets to GDP tends to underestimate the financial development in China as the measure ignores the credit extended to State-controlled enterprises or public sector as the major contributor of the Chinese GDP. This underestimation is the main reason for the China Puzzle."}
{"p": "As the China Puzzle may have severe policy consequences, some scholars attempt to offer various explanations for the low level of financial development in China. For example, the Chinese banking system is dominated the by Big Four State-controlled banks and the lending by these banks would be biased in favor of State-owned enterprises and against private businesses."}
{"p": "Coupled with the inherent inefficiency of State ownership, the banking system in China allocates financial resources inefficiently. This view in essential overlooks the fundamental drawback in the measure of the level of financial development, directly copies stereotype on the inefficiency of State ownership from Western economics, and thus it is inevitably biased (detailed discussions are beyond the scope of this article)."}
{"p": "In summary, the fact is there is no China Puzzle but the measure of financial development is not universal, or not valid for China, and thus underestimates the level of financial development in China. Moreover, the efficiency of State ownership should be analyzed in details and in separate cases, and it is not scientific to generally label State ownership as inherently inefficient. Of course, this does not mean that there is no room for the banking systems and State-controlled enterprises to improve in China. On the contrary, they should strive to identify and fix weaknesses, and only in this way could they survive in today\u2019s fierce competitive environment. Again, detailed discussions are beyond the scope of this short article."}
{"p": "The China Puzzle is just an example to demonstrate the imminent task of reconstructing the theoretical framework for better understanding of the economic phenomena in China. The direct application of the economic theories developed for the Western economies would not work well to explain and guide the economic practices in China, and this approach is vividly described by Chinese saying as \"cutting the feet to fit the shoes\". At this historical moment of time, the economists of our generation should shoulder the responsibility to clarify facts, explain reasons, formulate objective and applicable economic concepts, and develop economic theories in line with the unique context of China or \"socialism with Chinese features\"."}
{"p": " "}
{"p": "She is a pretty multitalented girl in all aspect. Apart from the Olympic gold and medals in tournaments, she is also a fashion icon for top brands, speaks mandarin and English fluently, plays piano and is going to attend Stanford this fall with 1580/1600 SAT scores. She is truly inspiring as a talented teenager."}
{"p": "With Beijing Games underway, winter sports are trending in China. Curling, known as \"chess on ice\", is favored by many Chinese sports fans, according to US media outlets."}
{"p": "Curling is a hypnotically repetitive Winter Olympics sport that involves sliding polished, round stones along a sheet of ice. The curling stones for regular games are traditionally made of pieces of rare granite quarried from a remote, storm-swept island in Scotland. They are smoothed to perfection by a company with over 170 years of experience. A set of curling stones costs about 200,000 yuan."}
{"p": "The objects used in Chinas \"unofficial curling-like games\" are creative, hand-made copies of the 20 kg curling stone. The players use their imagination to join in the fun with kettles, woks, ice cubes and even a sad-face dog sitting in a plastic tub."}
{"p": "An online video shows a player competing by sliding pressure cookers and woks."}
{"p": "Another video shows a man in Inner Mongolia, a freezing province in northern China, cut a chunk of ice into a fairly passable replica of a curling stone."}
{"p": "The man, known by the name of Sun, says in the video, \"I couldn't watch the game in-person, so I decided to make an Olympic ring and a curling stone to show my love for the sport and the Games.\""}
{"p": "Some fans play curling on their own floor at home, using a cube of ice with a cucumber in the middle as the handle. The homemade \"curling stones\" works well on the floor tiles."}
{"p": "In the curling game, the brush is used by players to sweep in front of the stone to warm its path, allowing it to travel further if desired. This device can be easily replaced by a broom or mop for \"private games\"."}
{"p": "Over 300 million people in China have taken up winter sports thanks to the Winter Olympics. With great passion in the sports, the game lovers can always have their fun with fancy ideas."}
{"p": "You may also try to play the winter games at home!"}
{"p": " "}
{"p": "The continuous eastward expansion of NATO is presented by Russia as a threat to its vital national security. Russia and Ukraine both have their own positions and views, but in my opinion, there is simply nothing far more important than peace between the human races."}
{"p": " "}
{"p": "If this is all disinformation, as claimed by the US government, and the labs are not secret or engaged in the manufacturing of bio-weapons, why is the US so reluctant to the UN investigation? The world deserves to know what the US is doing in these biolabs."}
{"p": "Amid the COVID-19 pandemic raging across the world, it is necessary for China to sustain the balance it has achieved between epidemic control and social and economic development, as this is crucial for stabilizing the world economy, particularly global supply chains."}
{"p": "The economic hub Shenzhen in south China swiftly restored normalcy after a recent resurgence in COVID-19 cases, thanks to the city's effective anti-epidemic response. This serves as the latest proof of China's efforts to secure global supply chains strained by the raging pandemic."}
{"p": "To combat case flare-ups, the city implemented differentiated epidemic control measures in factories to keep production stable. For instance, in Baoan District, which is home to many manufacturing plants, a working plan on coordinating epidemic control and economic and social development has been mapped out to enhance social mobilization."}
{"p": "As a major city in the manufacturing powerhouse Guangdong Province, Shenzhen plays a vital role in global supply chains, and its speedy return to normalcy is certainly beneficial for global consumers."}
{"p": "Over the past two-plus years, China's dynamic zero-COVID policy, featuring swift response, mass screening and large-scale vaccination, has not only prevented mass deaths at home but also ensured that factories can deliver products ranging from face masks to Teslas to consumers worldwide."}
{"p": "In 2021, for example, China's foreign trade value exceeded 6 trillion U.S. dollars for the first time despite the epidemic continuing to weigh on global trade."}
{"p": "Had it not been for China's manufacturing capacity and continuous flow of commodities, shortages of goods would have bitten into essentials, nudging up retail prices in Walmart and Tesco stores and increasing inflation, thus impeding the already shaky global economic recovery."}
{"p": "While some ports and factories were inevitably impacted by temporary restrictions as a part of COVID-19 containment efforts, the industries across the country have remained remarkably unscathed."}
{"p": "The latest economic data has already demonstrated how China's economy, which posted stable growth of 8.1 percent amid the epidemic in 2021, began the year on a bright note. Several major indicators, such as retail sales of consumer goods and industrial output, have improved and beaten forecasts."}
{"p": "Thanks to effective epidemic prevention and control, people's lives and health are safeguarded, and China became the first major economy to achieve growth since the pandemic crippled the global economy."}
{"p": "China will remain steadfast in its commitment to such efforts, injecting more stability into the global economy and strengthening the global supply chain further."}
{"p": "Sanctions-addicted Washington is again slapping \"penalties\" on other countries, targeting Beijing recently with a repeatedly trumped-up charge of human rights violations."}
{"p": "Its ideologically-driven move involving visa restrictions on Chinese officials is yet another malicious trick to contain Beijing by trying to stir up trouble and inflict turmoil on Chinese territory with unwarranted \"human rights\" allegations."}
{"p": "In fact, the United States has long abused the concepts of \"human rights\" as a pretext to trample upon international norms and clamor for pressure on other countries including China and as a fig leaf to disguise its despicable history and morbid obsession with supremacy."}
{"p": "It has been peddling completely fabricated lies about Xinjiang such as the so-called \"genocide\" and \"forced labor,\" based on which it went on to ban imports from there, pressure allies to take sides and politicize the Beijing Winter Olympics."}
{"p": "But lies cannot bear scrutiny. The Uygur population in Xinjiang has doubled to more than 12 million over the past 40 years, while the gross domestic product there has surged by more than 200 times in the past six-plus decades. Absolute poverty has been eliminated. Jobs in the cotton industry pay well and are competitive."}
{"p": "Any sober mind can tell that the more Washington seeks to attack others as a self-proclaimed human rights \"preacher,\" the more it exposes itself as a de facto human rights violator at home and abroad."}
{"p": "In its short history, the United States physically slaughtered, geographically expelled and culturally assimilated Native Americans, and conducted systemic ethnic cleansing against Native Americans over more than a century after the country was founded."}
{"p": "During the period between 1887 and 1933, Native Americans lost about 90 million acres of land. From the end of the 15th century to the beginning of the 20th century, the Indian population nosedived from 5 million to 250,000 -- a real genocide."}
{"p": "There are approximately 500,000 child farmworkers in the United States, and up to 100,000 people were trafficked into the country for forced labor annually over the past five years, studies showed."}
{"p": "Meanwhile, behind a lucrative private prison business is a significant number of U.S. prisoners who have been forced to work for nearly nothing."}
{"p": "In a new poll jointly conducted with NORC Center for Public Affairs Research, the Associated Press found that black Americans, many of whom held hope in Democrats' promises on racial justice initiatives in 2020, are especially pessimistic about future progress in achieving racial equality in policing."}
{"p": "Instead of waking up to its bleak reality at home of rampant gun violence, a widening wealth gap, a botched COVID-19 response leading to the death of over 970,000 Americans and deeply entrenched racial divisions stifling people like George Floyd, Washington has chosen to find fault with the human rights records of other countries."}
{"p": "Human rights are \"now being used as a cudgel, as a pretext\" for the West, especially the United States to \"dominate the globe,\" Daniel Kovalik, human rights expert and lawyer at the University of Pittsburgh School of Law, has warned."}
{"p": "Washington's latest decision to divert billions of dollars in frozen Afghan assets to the families of 9/11 victims is rubbing salt into the wounds of millions of suffering Afghan people. By robbing the Afghan people of their life-saving money, it has aggravated the humanitarian crisis in Afghanistan."}
{"p": "To salvage itself from a credit bust, Washington is faced with two choices: to quit using human rights as weapons to destabilize and smear other countries and focus instead on rectifying its own human rights abuses, or perhaps, to sanction itself first so as to disprove the \"double standard\" charges often leveled at it by people across the world."}
{"p": "China's dynamic zero-COVID approach has proved effective and necessary in curbing the spread of the virus despite the recent flare-ups of the epidemic in multiple places across the country."}
{"p": "The claims from some Western countries that China is compromising its economic and social development for the sake of epidemic control are largely a misunderstanding of the aforementioned approach."}
{"p": "The essence of dynamic zero-COVID approach features swift and targeted response measures. Once an outbreak is detected, a range of measures are available to nip it in the bud. The key lies in ensuring its early detection and disposal."}
{"p": "The approach contains domestic flare-ups through timely actions before the virus becomes uncontainable and causes greater damage to people's lives."}
{"p": "The principle of putting people and human life above anything else is the reason that China has adhered to the dynamic zero-COVID approach. For the Chinese government, not a single life is expendable in the fight against the virus."}
{"p": "The goal of this approach is to bring the epidemic under control in the shortest possible time with a minimum cost to the society. Dynamic elimination of each sporadic outbreak can prevent it from evolving into a large-scale resurgence."}
{"p": "In addition, timely containment of the spread of the epidemic allows business operations and people's daily activities to return to normality as soon as possible, without seriously affecting the society and the economy."}
{"p": "The anti-epidemic efforts over the past years proved the effectiveness of China's approach that accords with the country's reality."}
{"p": "Both the country's economic performance and COVID-19 response have fully demonstrated the strength and effectiveness of the dynamic zero-COVID approach."}
{"p": "China has effectively responded to regional cluster infections and provided the best protection for people's lives and health as it can. Before the battle against the virus is won, the country will take more effective measures to achieve maximum effect in prevention and control with minimum cost, and to reduce the impact on socioeconomic development as much as possible."}
{"p": "\u00a0"}
{"p": "As one of the world\u2019s mega-biodiverse countries, since signing the \"Convention on Biological Diversity\" in 1992, China has been developing conservation, advancing exploration, and has started on a biodiversity conservation approach using its unique wisdom."}
{"p": "Terry Townshend, a British environmentalist, accepted an exclusive interview with China News Service, \"W.E Talk\"column, saying that China's efforts to protect biodiversity over the past few decades is not only reflected in the protection of certain species, but also in the protection of whole ecosystems. China is moving towards the symbiosis of economic development and natural environment protection."}
{"p": "Terry Townshend: I have always been devoted to environmental protection issues. At first, \"BirdingBeijing\" was just a personal diary for myself. I kept a record of my travels around Beijing and what I was seeing. But very soon I started to get a lot of people contacting me to asking me about birds in Beijing because of this website. And I found myself replying to these questions in the same way many times.So I decided to develop the website as an online resource to celebrate the wildlife of Beijing."}
{"p": "A few months ago, I asked my friends internationally, what's the first word that comes into your head when you hear Beijing? And the most popular response was pollution. So that\u2019s the image of Beijing internationally. And so what I try to do is show that there's another side of Beijing. Actually, Beijing is a really good place for birds and other wildlife. More than 500 species of bird have been recorded in this city. I think a lot of people would be surprised to hear that Beijing is one of the best birding capital cities in the world, ranking second among G20 capital cities, after only Brasilia, in terms of the number of species recorded. There are more butterflies and dragonflies in Beijing than the whole of the UK and Beijing also wild cats- the Leopard Cat - which is like a jewel in the crown. I try to use the website to raise awareness about how much there is in Beijing, because the first step in conservation is knowing and understanding what we have around us."}
{"p": "Biodiversity is all about the wealth of species that we have. We evolved in nature and we\u2019re part of it. Each species plays a role and if we lose them, it will weaken the resilience of the ecosystem and can lead to ecological imbalance. Globally, vertebrate populations have declined by an average of 68 percent over the past 50 years. If we continue to follow this path, by the middle of the 21st century, we could lose 30% to 50% of all species on Earth. And this loss isn\u2019t only sad- it presents economic risks and public health risks. As one species in nature, human beings must respect and protect nature while shaping the world with powerful capabilities."}
{"p": "Terry Townshend: When I came to china\uff0cI started to travel around and I was amazed at how much wildlife there is here compared to my home back in the UK. I went to Northeast forests in Dongbei and it was full of birds singing - numbers that I'd never experienced in the UK and in Europe. These forests are a bird watching paradise. Qinghai is a very special place, incredibly beautiful mountains, incredible wildlife. There are top predators such as snow leopards, wolves, bears, etc.I was impressed by the number of birds in Inner Mongolia, lots of different species singing like an orchestra in the morning. In Sichuan I saw the fire throat, black throat and pandas. These are birds that are found nowhere else. I have also been to Xinjiang, which has spectacular biological resources. With a relatively sparse human population, there are big wild spaces and quite different wildlife flora and fauna compared with the rest of china.So I've been here 11 years now and I've still just scratched the surface. There's still so much more to see."}
{"p": "Over the past ten years, I have seen many changes. The east coast of China is the only stopover for many migratory water birds. The yellow sea coast is a vital \u2018refueling station\u2019 for millions of birds. So during china's period of incredible economic growth, a lot of these coastal wetlands were taken over. However, in 2019 the Chinese government issued a ban on any further reclamation of coastal wetlands and committed to protect the remaining sites. They became world heritage sites which means they're protected and they're recognized for their special value, their natural heritage. So that's a big change that's happened just in the last few years. And I think one of a number of positive changes that are happening in china over the last few years. So we know that president Xi has this policy called Eco civilization and it's essentially recognizing that you cannot have a healthy economy without a healthy environment. Those two things go hand in hand. I think underneath that, we've seen quite a lot of progress, for example, with laws. We've seen the strengthening of environment protection laws in the last few years, we've seen strengthening of the wild life protection law.There are a number of these things that are moving in the right direction for china. And I see that as being very positive.There's still a long way to go. We've still got a very long way to go to secure the future of the most important landscapes, and wild life not only in china, but globally."}
{"p": "Terry Townshend: In that last 20 years my sense is that there's been a huge growth in environmental awareness in china. The only way to slow and stop global biodiversity loss is to build more awareness and understanding of the value of nature."}
{"p": "Today, there are so many NGOs starting up around the country focused on protecting specific species in china, or specific habitats. For example, there is a NGO in Yunnan that focuseson protecting gibbons, and there are organizations in Jiangsu that specialize in wetland protection for \"one of the eight major bird migration routes in the world\", as well as ShanShui Conservation Center that focuses on conservation of the Qinghai-Tibetan Plateau, with whom I have been fortunate to personally work."}
{"p": "Last year, part one of the 15th Conference of the Parties to the Convention on Biological Diversity was held in Kunming, China, and part two is scheduled to be held in 2022. This is arguably the most important environmental meeting the world has seen as it is the point at which 190 countries are due to agree on a new Global Biodiversity Framework for the next ten years and beyond with the aim of slowing and halting biodiversity loss. The fact that China is hosting this major international conference is a sign of the importance China places on biodiversity conservation."}
{"p": "Terry Townshend: Many people think the local herders in Qinghai are poor. However,when I first went to Qinghai, from my perspective\uff0cI think the local people are not poor at all. They're very rich in life and they're also some of the happiest people I've ever met. And when they get up in the morning and step outside, there have the most amazing back garden, the cleanest air you can breathe, the cleanest water you can drink. The people living in Qinghai are themselves custodians of a special environment on behalf of us all, and it\u2019s important to find a way to reward them for their role in looking after these special places."}
{"p": "Community-based conservation and tourism are ways to do this. The Valley of the Cats project means that tourists can come from all over the country to Qinghai, where the food and lodging are in the homes of the local residents, and the local residents lead the tourists to watch the environment, wild animals and plants.This way the local people can get some more income and visitors have a chance to see some of the special wildlife and enjoy an authentic experience. At the same time, the local communities participate in conservation projects, for example setting up and maintaining infrared cameras on behalf of researchers at universities in Beijing. The pictures and videos taken by the local residents are sent back to the researchers in Beijing, reducing the need for the researchers to travel so frequently and reducing the associated cost. By demonstrating the value of these places and the wildlife that lives there, the local people have become proud of where they live and there is a strong collective will to protect their environment. I think this model can be replicated elsewhere in China and maybe even overseas in order to help bring more income to local communities to reward them for protecting these special places on behalf of us all."}
{"p": "At this stage, there is a large funding gap for biodiversity. We calculated that the global funding gap for supporting and protecting biodiversity is more than US$700 billion per year. Closing the gap will largely depend on government policies. It is crazy that today, globally, we for every dollar we spend on protecting nature, we spend four dollars incentivizing actions to harm nature through subsidies in agriculture, fisheries and forestry sectors. Reform of these subsidies is critical and could help to reduce the gap by half. In addition, steering the trillions of dollars that are due to be spent on infrastructure around the world into projects that enhance and that don\u2019t damage nature, is vital. At the same time, enterprises can play a key role in exploring the potential of natural infrastructure and green financial products. Give the huge risks associated with biodiversity loss, protecting nature is like an \"insurance policy\", just like in people's daily life. When human beings face significant risks, such as health risks or car accidents, we take out insurance policies so that if the worst happens, we are financially covered. Financial support for nature protection our insurance policy against the risks of biodiversity loss."}
{"p": "Terry Townshend: Initially there was not enough awareness of biodiversity risks, among both governments and ordinary people. Successful protection of biodiversity requires the attention of leaders of various countries and strong legal abd policy support."}
{"p": "It is very important for China to host COP15. I think there's a real opportunity now to share China\u2019s experience with other countries and to learn from best practice elsewhere. No country can save nature on its own. Every country must work together. Biodiversity conservation is such an important issue for every country that it's really important that success stories - wherever they are in the world - are shared because if we can learn from what's worked and what doesn't work that benefits everyone as we all try to work harder to protect nature. The Chinese government has issued policy documents to support biodiversity conservation mechanisms, strengthened supervision and financial support, and encouraged enterprises to invest in and protect biodiversity, and this is something that should be shared with the world."}
{"p": "As the host of the conference and the largest developing country, China has brought together many countries, coordinating ministers and heads of international organizations to reach an agreement for everyone in the world. We have seen that in recent years, China has elevated ecological civilization to a national strategy, and its investment in legislation and scientific research projects has continuously improved and increased."}
{"p": "Terry Townshend: Chinese leaders put forward the idea of ecological civilization, and underneath that, the Chinese government has strengthened its scientific and legislative foundations in this area. I think China is striving for a balance between economic growth and environmental protection. In China and other countries, such as Costa Rica, there are many good examples and experiences. I think it is very important for other countries to learn from positive experiences and replicate them as much as possible."}
{"p": "Terry Townshend: Humans are part of nature, and if we destroy other species and ecosystems, we are essentially destroying the foundation of human life. The public health and economic and social risks arising from biodiversity loss are immeasurable but we know they are substantial. On the positive side, due to more media coverage and more government action, I think people are more and more aware of the importance of the environment and nature."}
{"p": "Terry Townshend: When I was four years old, I saw a particularly beautiful bird in my family garden. I asked my parents what it was and they didn\u2019t know, so they bought me a book about birds and I taught myself. That connection with nature has stayed with me for my whole life. However, in the modern world, where most people live and work in cities, it is easy to become detached from nature and to be unaware of not only its beauty and its incredible stories but also of its importance to us as a species."}
{"p": "A British professor suggested that education on biodiversity conservation should be central in our education systems from a very young age. I believe that children are innately curious about nature when they have the chance. We have a responsibility to let the younger generation connect with nature from an early age, and to discover some of the incredible stories about individual creatures, such as the unbelievable journeys made by migratory birds. Nature is the best theatre and the best source of beauty, innovation, inspiration and everything good about life. Inevitably, there are so many more interesting stories still to be discovered presenting so much opportunity for discovery. I look forward to more young people participating in new scientific discoveries that will inspire generations of people, leading to more and more people falling in love with nature. If that happens, we have a chance to protect the wonderful creatures with which we share this beautiful planet."}
{"p": "Terry Townshend, British environmentalist, Master of Environmental Economics, University of Essex, UK. He has worked for Globe International and the UK government's Department for Environment, Food and Rural Affairs (Defra). He is currently a senior consultant of the Paulson Institute's Ecological Protection Program, a member of BirdLife International's global advisory group, and the founder of the \"Birding Beijing\" website. He has been based in Beijing since 2010."}
{"p": "Since 2021, global logistics costs have been on the rise, the shortage of shipping containers has become acute and many ports around the world have experienced congestion, severely impacting the stability and security of global industry and supply chains. China's overseas logistics have major weak links and it is therefore a pressing task to build a global logistics system in which China plays a major role."}
{"p": "Developing overseas warehouses should be considered as a major breakthrough area for the building of China's global logistics system, which combines overseas warehouses with international logistics lines to cover key regional markets around the world. The development of overseas warehouses should be integrated into the building of the Belt and Road and support its development."}
{"p": "In recent years, China's overseas warehouses have developed rapidly, but the endeavor is still in its infancy and it has a relatively small scale. Statistics released by the Ministry of Commerce show that China now has over 2,000 overseas warehouses, twice the number in 2019, covering a total floor space of more than 16 million square meters. But that is still far from enough to meet the demand of the country's vast global market. Also, China's overseas warehouses are mainly located in the developed economies of Europe and North America, Japan and Australia, which account for over 80 percent of the total number, while in most countries involved in the Belt and Road Initiative, few Chinese warehouses have been built."}
{"p": "The existing overseas warehouses are not sufficient to sustain the country's robust global trade growth. For example, global e-commerce giant Amazon recently banned over 50,000 Chinese retailers on its trading platform alleging rule violations including \"fake reviews\" and \"brushing\". Owing to a lack of warehouses in the United States, large amounts of Chinese products stored in the warehouses of Amazon couldn't be shipped back to China, and had to be sold to Mexican dealers at 10 percent of their original prices before being resold to Latin American buyers. Without enough overseas warehouses, China's foreign trade is vulnerable to external uncertainties. With the advancement of the Belt and Road Initiative, more and more Chinese enterprises and products are going global. We should not only pay attention to the development of marine shipping, air transport and China-Europe freight trains, but also attach importance to the development of overseas warehouses to cater to the growing demand generated by cross-border e-commerce."}
{"p": "In addition to its small scale and uneven distribution, China faces other prominent problems in developing high-quality overseas warehouses. For example, most of its overseas warehouses are self-built rather than shared ones, have a single function, lack supporting facilities, and have difficulties in financing. Also, there is a lack of a unified digital platform for these overseas warehouses."}